import type { Insumo, Operacional } from "./calc";

export const INSUMOS_BAIXO_INIT: Insumo[] = [
  { produto: "TEBURAZ-BD20", quantidade: 0.5, familia: "FUNGICIDA", valor: 47.73 },
  { produto: "BLAVITY-GL05", quantidade: 0.25, familia: "FUNGICIDA", valor: 387.49 },
  { produto: "FUSAO EC-GL05", quantidade: 0.6, familia: "FUNGICIDA", valor: 90.95 },
  { produto: "ABSOLUTO FIX - BD20", quantidade: 1, familia: "FUNGICIDA", valor: 32.22 },
  { produto: "FASTAC 100 SC -GL05", quantidade: 0.4, familia: "INSETICIDA", valor: 45.13 },
  { produto: "TERMINUS-GL10", quantidade: 0.25, familia: "INSETICIDA", valor: 131.03 },
  { produto: "TALISMAN-GL05", quantidade: 0.6, familia: "INSETICIDA", valor: 74.4 },
  { produto: "Brafix -SOJA 2025", quantidade: 1, familia: "BIOLÓGICO", valor: 20 },
  { produto: "Auba-SOJA 2025", quantidade: 0.4, familia: "BIOLÓGICO", valor: 200 },
  { produto: "Tritter-SOJA 2025", quantidade: 0.1, familia: "BIOLÓGICO", valor: 390 },
  { produto: "AllNutri-20 LT", quantidade: 1, familia: "FOLIAR", valor: 21.4 },
  { produto: "Nutruss Man-20 LT", quantidade: 1, familia: "FOLIAR", valor: 19.25 },
  { produto: "Mutto - 5LT", quantidade: 0.2, familia: "FOLIAR", valor: 241.28 },
  { produto: "HEAVY-20 LT", quantidade: 5, familia: "FOLIAR", valor: 20.98 },
  { produto: "Fullgrain-20 LT", quantidade: 2, familia: "FOLIAR", valor: 20.33 },
  { produto: "Mageos--20 LT", quantidade: 1, familia: "FOLIAR", valor: 26.35 },
  { produto: "ZAFERA-SC20", quantidade: 4, familia: "HERBICIDA", valor: 26.14 },
  { produto: "ASSIST EC-BD20", quantidade: 1.25, familia: "OLEO MINERAL", valor: 29.15 },
  { produto: "Spray Max-SOJA 2025", quantidade: 0.25, familia: "ADJUVANTE", valor: 68 },
  { produto: "SEMENTE DE SOJA TORMENTA", quantidade: 0.052, familia: "SEMENTE", valor: 13243.3 },
  { produto: "07-45-00 ROB", quantidade: 0.18, familia: "FERTILIZANTE", valor: 7583 },
  { produto: "KCL GR", quantidade: 0.1, familia: "FERTILIZANTE", valor: 3346 },
  { produto: "FRETE CARRETA - 60 KMs", quantidade: 0.28, familia: "FRETE", valor: 53 },
];

export const INSUMOS_ALTA_INIT: Insumo[] = [
  { produto: "ONSUVA-GL05", quantidade: 0.3, familia: "FUNGICIDA", valor: 359.68 },
  { produto: "BELYAN-GL05", quantidade: 0.6, familia: "FUNGICIDA", valor: 427.1 },
  { produto: "BLAVITY-GL05", quantidade: 0.25, familia: "FUNGICIDA", valor: 439.9 },
  { produto: "KEYRA-GL10", quantidade: 0.5, familia: "FUNGICIDA", valor: 178.77 },
  { produto: "FASTAC 100 SC -GL05", quantidade: 0.4, familia: "INSETICIDA", valor: 48.18 },
  { produto: "BRIGHT-GL05", quantidade: 0.25, familia: "INSETICIDA", valor: 124.07 },
  { produto: "TALISMAN-GL05", quantidade: 0.6, familia: "INSETICIDA", valor: 69.09 },
  { produto: "ZEUS-GL10", quantidade: 0.5, familia: "INSETICIDA", valor: 72.64 },
  { produto: "Brafix -SOJA 2025", quantidade: 1, familia: "BIOLÓGICO", valor: 30 },
  { produto: "Auba-SOJA 2025", quantidade: 0.4, familia: "BIOLÓGICO", valor: 220 },
  { produto: "Tritter-SOJA 2025", quantidade: 0.15, familia: "BIOLÓGICO", valor: 360 },
  { produto: "Bettus-SOJA 2025", quantidade: 0.5, familia: "BIOLÓGICO", valor: 50 },
  { produto: "AllNutri-20 LT", quantidade: 1, familia: "FOLIAR", valor: 28 },
  { produto: "Nutruss Man-20 LT", quantidade: 1, familia: "FOLIAR", valor: 23 },
  { produto: "Mutto - 5LT", quantidade: 0.25, familia: "FOLIAR", valor: 270 },
  { produto: "HEAVY-20 LT", quantidade: 6, familia: "FOLIAR", valor: 27 },
  { produto: "Fullgrain-20 LT", quantidade: 4, familia: "FOLIAR", valor: 23 },
  { produto: "Mageos--20 LT", quantidade: 1, familia: "FOLIAR", valor: 32 },
  { produto: "Imncito-20 LT", quantidade: 1, familia: "FOLIAR", valor: 25 },
  { produto: "7-45-00NPS ROBUSTTO", quantidade: 0.22, familia: "FERTILIZANTE", valor: 7583 },
  { produto: "KCL CONVENCIONAL", quantidade: 0.15, familia: "FERTILIZANTE", valor: 3346 },
  { produto: "FRETE CARRETA - 60 KMs", quantidade: 0.37, familia: "FERTILIZANTE", valor: 53 },
  { produto: "ZAFERA-SC20", quantidade: 4, familia: "HERBICIDA", valor: 34.66 },
  { produto: "POQUER-BD20", quantidade: 1.4, familia: "HERBICIDA", valor: 48 },
  { produto: "AURORA 400 EC-GL05", quantidade: 0.1, familia: "HERBICIDA", valor: 454.14 },
  { produto: "ASSIST EC-BD20", quantidade: 1.25, familia: "OLEO MINERAL", valor: 20.54 },
  { produto: "Spray Max-SOJA 2025", quantidade: 0.25, familia: "ADJUVANTE", valor: 67 },
  { produto: "SEMENTE DE SOJA TORMENTA", quantidade: 0.05, familia: "SEMENTE", valor: 12314 },
];

export const OPERACIONAL_INIT: Operacional = {
  baixo: { plantio: 350, colheita: 250, manutencao: 400, outros: 300 },
  alta: { plantio: 350, colheita: 350, manutencao: 400, outros: 300 },
};
